/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.demo.myapp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Myapp service. Represents a row in the &quot;MyApp_Myapp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.demo.myapp.model.impl.MyappModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.demo.myapp.model.impl.MyappImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Myapp
 * @generated
 */
@ProviderType
public interface MyappModel
	extends BaseModel<Myapp>, GroupedModel, ShardedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a myapp model instance should use the {@link Myapp} interface instead.
	 */

	/**
	 * Returns the primary key of this myapp.
	 *
	 * @return the primary key of this myapp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this myapp.
	 *
	 * @param primaryKey the primary key of this myapp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the myapp ID of this myapp.
	 *
	 * @return the myapp ID of this myapp
	 */
	public long getMyappId();

	/**
	 * Sets the myapp ID of this myapp.
	 *
	 * @param myappId the myapp ID of this myapp
	 */
	public void setMyappId(long myappId);

	/**
	 * Returns the group ID of this myapp.
	 *
	 * @return the group ID of this myapp
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this myapp.
	 *
	 * @param groupId the group ID of this myapp
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this myapp.
	 *
	 * @return the company ID of this myapp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this myapp.
	 *
	 * @param companyId the company ID of this myapp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this myapp.
	 *
	 * @return the user ID of this myapp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this myapp.
	 *
	 * @param userId the user ID of this myapp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this myapp.
	 *
	 * @return the user uuid of this myapp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this myapp.
	 *
	 * @param userUuid the user uuid of this myapp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this myapp.
	 *
	 * @return the user name of this myapp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this myapp.
	 *
	 * @param userName the user name of this myapp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this myapp.
	 *
	 * @return the create date of this myapp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this myapp.
	 *
	 * @param createDate the create date of this myapp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this myapp.
	 *
	 * @return the modified date of this myapp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this myapp.
	 *
	 * @param modifiedDate the modified date of this myapp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this myapp.
	 *
	 * @return the title of this myapp
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this myapp.
	 *
	 * @param title the title of this myapp
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this myapp.
	 *
	 * @return the description of this myapp
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this myapp.
	 *
	 * @param description the description of this myapp
	 */
	public void setDescription(String description);

	/**
	 * Returns the article ID of this myapp.
	 *
	 * @return the article ID of this myapp
	 */
	public long getArticleId();

	/**
	 * Sets the article ID of this myapp.
	 *
	 * @param articleId the article ID of this myapp
	 */
	public void setArticleId(long articleId);

	/**
	 * Returns the status of this myapp.
	 *
	 * @return the status of this myapp
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this myapp.
	 *
	 * @param status the status of this myapp
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this myapp.
	 *
	 * @return the status by user ID of this myapp
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this myapp.
	 *
	 * @param statusByUserId the status by user ID of this myapp
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this myapp.
	 *
	 * @return the status by user uuid of this myapp
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this myapp.
	 *
	 * @param statusByUserUuid the status by user uuid of this myapp
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this myapp.
	 *
	 * @return the status by user name of this myapp
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this myapp.
	 *
	 * @param statusByUserName the status by user name of this myapp
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this myapp.
	 *
	 * @return the status date of this myapp
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this myapp.
	 *
	 * @param statusDate the status date of this myapp
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this myapp is approved.
	 *
	 * @return <code>true</code> if this myapp is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this myapp is denied.
	 *
	 * @return <code>true</code> if this myapp is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this myapp is a draft.
	 *
	 * @return <code>true</code> if this myapp is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this myapp is expired.
	 *
	 * @return <code>true</code> if this myapp is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this myapp is inactive.
	 *
	 * @return <code>true</code> if this myapp is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this myapp is incomplete.
	 *
	 * @return <code>true</code> if this myapp is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this myapp is pending.
	 *
	 * @return <code>true</code> if this myapp is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this myapp is scheduled.
	 *
	 * @return <code>true</code> if this myapp is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}